version: "3"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      REDIS_SERVER: redis://redis:6379
    depends_on:
      - redis
    ports:
      - 3000:3000
      - 3001:3001
  redis:
    image: redis:7
    ports:
      - 6379:6379